# Generated by Django 6.0.3 on 2026-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
